# Generated by Django 4.2.6 on 2023-10-24 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_entidad_comunicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.entidad'),
        ),
    ]
