# Generated by Django 4.2.6 on 2023-10-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_comunicado_publicado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='publicado_por',
            new_name='modificado_por',
        ),
    ]
