# Generated by Django 4.2.6 on 2023-10-24 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_rename_publicado_por_comunicado_modificado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entidad',
        ),
        migrations.AddField(
            model_name='user',
            name='entidadPerteneciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.entidad'),
        ),
    ]
